apiVersion: v1
kind: Service
metadata:
  name: {{ include "v8-1c-cluster-extractor.fullname" . }}
  labels:
    {{- include "v8-1c-cluster-extractor.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "v8-1c-cluster-extractor.selectorLabels" . | nindent 4 }}
